'use strict';
const app=document.querySelector('#app'), modal=document.querySelector('#modal'), modalBody=document.querySelector('#modal-body');
let me=null, engineers=[], requests=[], selectedSpecialty='全部', searchTerm='', poll=null, currentMessages='', routeToken=0;
const specialties=[
 {name:'机械工程',icon:'⚙',en:'MECHANICAL',desc:'从一个齿轮开始，理解机器如何运转。',intro:'机械工程研究如何设计、制造和改进机器，把一个想法变成可以运转的实物。',courses:['工程制图与 CAD','理论力学与材料力学','机械设计与制造','控制基础与机器人'],jobs:'机械设计、制造工艺、机器人与自动化设备研发。',example:'设计一台桌面机械臂：先画出关节和传动结构，再比较夹爪材料，最后测试抓取的稳定性。',project:'用纸板、螺栓和橡皮筋制作一个可活动的抓手，记录它能抓住哪些不同形状的物体。'},
 {name:'电子工程',icon:'⌁',en:'ELECTRONICS',desc:'连接电路，让小小的信号改变世界。',intro:'电子工程关注电路、信号和电子系统，帮助我们感知、计算与控制周围的世界。',courses:['电路原理','模拟与数字电子技术','信号与系统','单片机与嵌入式系统'],jobs:'硬件设计、芯片测试、通信系统和嵌入式开发。',example:'自动浇水装置通过土壤湿度传感器判断是否缺水，再控制水泵的开启时间。',project:'使用低压开发板搭建光照提醒器，比较白天与夜晚读数。由指导老师协助接线，避免接触市电。'},
 {name:'土木工程',icon:'⌂',en:'CIVIL',desc:'让桥梁与建筑，承载更好的生活。',intro:'土木工程研究建筑、桥梁、道路等基础设施的结构、施工与维护，关注安全、可靠与环境适应性。',courses:['结构力学','土木工程材料','钢结构与混凝土结构','工程测量与施工组织'],jobs:'结构设计、工程建设、城市基础设施与项目管理。',example:'桥梁的桁架结构把荷载分散到不同杆件，在较少的材料下实现更强的承载能力。',project:'用纸和胶带制作同跨度的三种桥梁模型，逐步加上小砝码，比较承载能力。'},
 {name:'环境工程',icon:'♧',en:'ENVIRONMENTAL',desc:'用工程思维，守护我们共同的家园。',intro:'环境工程利用科学和工程方法减少污染、处理废水和废弃物，并提高资源利用效率。',courses:['环境化学','水处理工程','大气污染控制','环境监测与资源循环'],jobs:'水处理、环保设备、环境监测、资源回收和可持续发展。',example:'雨水花园通过土壤和植物滞留雨水，减轻排水压力并减少地表径流。',project:'用砂石和滤纸制作过滤模型，对比过滤前后的浑浊程度。过滤后的实验用水不可饮用。'},
 {name:'计算机工程',icon:'⌘',en:'COMPUTER',desc:'在代码与硬件之间，创造新的可能。',intro:'计算机工程结合软硬件，研究计算系统如何工作，以及如何构建高效、可靠的应用。',courses:['程序设计','数据结构','计算机组成原理','操作系统与计算机网络'],jobs:'软件开发、系统工程、物联网与智能设备研发。',example:'智能垃圾分类装置组合图像识别、控制软件和机械机构，让识别结果驱动分拣动作。',project:'编写一个记录校园植物的网页，用表格存储观察日期、地点和生长变化。'},
 {name:'航空航天',icon:'↗',en:'AEROSPACE',desc:'把目光投向天空，把想象落到实处。',intro:'航空航天工程研究飞行器的空气动力学、结构、动力与控制，从飞机到航天器都需要多领域协作。',courses:['空气动力学','飞行力学','飞行器结构','推进原理与控制系统'],jobs:'飞行器设计、结构分析、制造测试与飞行控制。',example:'滑翔机通过机翼产生升力，翼形、重心与尾翼配置共同影响飞行稳定性。',project:'制作不同翼形的纸滑翔机，在同一环境和投掷方式下比较飞行距离，记录重心的影响。'}
];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>new Date(v*1000).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});
async function api(path,data){const r=await fetch('/api/'+path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined});const result=await r.json();if(!r.ok)throw new Error(result.error||'暂时无法连接，请稍后再试。');return result;}
function toast(text){const t=document.querySelector('#toast');t.textContent=text;t.classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('visible'),4000);}
function showModal(html){modalBody.innerHTML=html;if(!modal.open)modal.showModal();}
function formError(form,text){const error=form.querySelector('.error');error.textContent=text;error.classList.add('visible');}
function errorBox(){return '<div class="error" role="alert"></div>';}
async function formSubmit(form,fn){const button=form.querySelector('button[type=submit]');button.disabled=true;form.querySelector('.error')?.classList.remove('visible');try{await fn(new FormData(form));}catch(e){formError(form,e.message);}finally{button.disabled=false;}}
const roleName=u=>u?.is_admin?'管理员':u?.role==='engineer'?'工程师':'学生';
function accountLabel(){
 document.querySelector('#account').textContent=me?`${me.name} · ${roleName(me)}`:'登录 / 注册 ↗';
 const nav=document.querySelector('nav');
 nav.innerHTML=me?.is_admin?'<a href="#admin">管理总览</a><a href="#admin/users">全部用户</a><a href="#admin/requests">全部咨询</a><a href="#student">学生端预览</a><a href="#mentor">工程师端预览</a>':me?.role==='engineer'?'<a href="#mentor">工程师工作台</a><a href="#workspace">指导项目</a><a href="#profile">个人资料</a><a href="#student">浏览学生端</a><a href="#about">关于我们</a>':'<a href="#home">学生首页</a><a href="#engineers">寻找工程师</a><a href="#explore">探索工程</a><a href="#workspace">我的咨询</a><a href="#about">关于我们</a>';
}
function art(){return `<div class="hero-art"><svg viewBox="0 0 470 420" aria-label="机械臂与小小探索者的工程线稿" role="img"><defs><pattern id="grid" width="26" height="26" patternUnits="userSpaceOnUse"><path d="M26 0H0V26" fill="none" stroke="#cad4c4" stroke-width=".6"/></pattern></defs><rect width="470" height="420" fill="url(#grid)"/><circle cx="247" cy="203" r="148" fill="none" stroke="#acbcaa" stroke-width="1" stroke-dasharray="4 7"/><g stroke="#355c49" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"><path d="M77 323h317M199 323v-32h90v32M218 291v-28h52v28M242 263l-40-86 18-13 65 91M203 178l84-93 18 14-73 102M288 88l73 50-12 17-52-36M351 149l17 20-7 19M349 158l-2 25-15 5"/><circle cx="214" cy="183" r="19" fill="#e8ecdf"/><circle cx="214" cy="183" r="8"/><circle cx="295" cy="99" r="17" fill="#e8ecdf"/><circle cx="295" cy="99" r="6"/><circle cx="254" cy="265" r="14" fill="#e8ecdf"/><circle cx="254" cy="265" r="5"/><path d="M117 323l4-68 38-2 17 70M130 321l5-41M151 278l11 44M123 255l-7-33 30-20 21 45-8 7M149 218l39-24M157 231l35-29M114 227l-13 25-22-7"/><circle cx="129" cy="186" r="17" fill="#f4eddd"/><path d="M114 184q13-24 31 0M74 244l-3-19 11-5 9 18M320 304h57v19h-57zM320 304l24-26 33 26M344 278v26M89 102h55v42H89zM97 111h38M97 119h21M97 132h28M336 65l9-12 9 12M345 53v27"/><path d="M57 177h30M72 162v30M381 233h22M392 222v22" stroke="#e98246"/></g><circle cx="295" cy="99" r="4" fill="#e98246"/><circle cx="214" cy="183" r="5" fill="#e98246"/><path d="M190 352h145" stroke="#aebda8" stroke-dasharray="3 6"/><text x="187" y="377" fill="#758570" font-size="10" letter-spacing="3">IDEA → DESIGN → CREATE</text></svg><div class="art-tag"><span>✳</span> 每一个好奇，值得一个答案</div></div>`;}
function engineerCard(e){return `<article class="card engineer-card"><div class="card-top"><div class="avatar">${esc(e.name[0])}</div><div><h3>${esc(e.name)}</h3><p>${esc(e.specialty)} · ${e.years} 年从业经验</p></div></div><span class="badge">${esc(e.fee)}</span><p class="bio">${esc(e.bio||'这位工程师正在完善个人介绍。可以预约沟通你的项目想法。')}</p><div class="card-meta"><span>开放预约</span><span>项目指导 · 经验分享</span></div><button class="button secondary" data-book="${e.id}">预约指导 ↗</button></article>`;}
function engineerEmpty(){return `<div class="empty wide"><h3>第一位引路人，会是你吗？</h3><p>目前还没有开放预约的工程师。欢迎退休工程师入驻，分享专业经验，陪伴学生完成第一个项目。</p><button class="button secondary" data-join>以工程师身份加入 ↗</button></div>`;}
function home(){app.innerHTML=`<div class="page"><section class="hero"><div><div class="eyebrow">A NEW CHAPTER FOR EXPERIENCE</div><h1>让你的好奇心，<br>遇见<em>一生的经验。</em></h1><p>与退休工程师一起，把想法变成真正的工程项目。<br>从专业探索到动手实践，总有一位前辈为你引路。</p><div class="actions"><a class="button" href="#engineers">寻找我的工程师 <span>↗</span></a><a class="button secondary" href="#explore">探索工程专业</a></div><div class="hero-note"><strong>✳ 公益与低收费指导</strong><span>从第一次提问，到第一个作品</span></div></div>${art()}</section><section class="journey" aria-label="开始探索"><a href="#explore"><span class="num">01</span><div><h3>发现你的兴趣</h3><p>认识专业，找到想探索的方向</p></div><span class="arrow">↗</span></a><a href="#engineers"><span class="num">02</span><div><h3>遇见你的引路人</h3><p>寻找与你的项目匹配的工程师</p></div><span class="arrow">↗</span></a><a href="#workspace"><span class="num">03</span><div><h3>让想法落地</h3><p>提问、讨论，一起推进项目</p></div><span class="arrow">↗</span></a></section><div class="home-bottom"><section><div class="section-head"><div><div class="eyebrow">MEET YOUR MENTOR</div><h2>经验，正等着传递</h2><p>找到愿意陪你迈出第一步的前辈。</p></div><a class="text-link" href="#engineers">全部工程师 ↗</a></div><div class="card">${engineers.length?engineers.slice(0,3).map(e=>`<div class="engineer-mini"><div class="avatar">${esc(e.name[0])}</div><div class="mini-content"><h3>${esc(e.name)}</h3><p>${esc(e.specialty)} · ${e.years} 年经验</p><span class="badge">${esc(e.fee)}</span></div><button class="icon-button" data-book="${e.id}" aria-label="预约${esc(e.name)}">↗</button></div>`).join(''):engineerEmpty()}</div></section><section><div class="section-head"><div><div class="eyebrow">A LITTLE INSPIRATION</div><h2>从一个问题开始</h2><p>工程的世界，比你想象的更近。</p></div></div><div class="feature-card"><div class="eyebrow">土木工程 · 项目灵感</div><h3>一张纸，能撑起<br>多大的重量？</h3><p>试着改变桥梁的结构，发现隐藏在日常里的工程智慧。</p><a class="text-link" href="#specialty/2">探索纸桥实验 ↗</a><svg viewBox="0 0 200 190" aria-hidden="true"><g stroke="#866c47" fill="none" stroke-width="2"><path d="M10 160h190M20 155v-65h160v65M20 90l40 45 40-45 40 45 40-45M20 135h160M60 135V90M100 90v45M140 135V90M20 90l40-40 40 40 40-40 40 40M60 50h80M60 50v40M140 50v40"/></g></svg></div></section></div></div>`;}
function engineerList(){const visible=engineers.filter(e=>(selectedSpecialty==='全部'||e.specialty===selectedSpecialty)&&`${e.name} ${e.bio} ${e.specialty}`.toLowerCase().includes(searchTerm.toLowerCase()));app.innerHTML=`<div class="page"><div class="page-intro"><div class="eyebrow">FIND YOUR MENTOR</div><h1>找一位前辈，一起把想法做出来。</h1><p>按工程方向寻找指导者，告诉他们你的项目和正在遇到的问题。</p></div><div class="toolbar"><label class="sr-only" for="engineer-search">搜索工程师</label><input class="search" id="engineer-search" value="${esc(searchTerm)}" placeholder="搜索姓名、专业或项目关键词"><button class="button secondary" id="engineer-search-button">搜索</button><button class="button" data-join>我是工程师，加入工坊 ↗</button></div><div class="chips">${['全部',...specialties.map(s=>s.name)].map(s=>`<button class="chip ${s===selectedSpecialty?'active':''}" data-filter="${s}">${s}</button>`).join('')}</div><p class="inline-note">${visible.length} 位工程师开放预约 · 资料由本人填写，平台尚未进行资质认证</p><div class="grid">${visible.length?visible.map(engineerCard).join(''):engineers.length?'<div class="empty wide">没有找到匹配的工程师，请尝试其他专业或关键词。</div>':engineerEmpty()}</div></div>`;}
function explore(){app.innerHTML=`<div class="page"><div class="page-intro"><div class="eyebrow">EXPLORE ENGINEERING</div><h1>世界的运转，藏着多少种可能？</h1><p>了解工程专业、大学课程与真实应用，从一个小项目开始探索。</p></div><div class="grid">${specialties.map((s,i)=>`<a class="card specialty-card" href="#specialty/${i}"><span class="number">0${i+1} / ${s.en}</span><span class="specialty-icon">${s.icon}</span><h3>${s.name}</h3><p>${s.desc}</p><span class="text-link">认识这个专业 ↗</span></a>`).join('')}</div><p class="hint">课程与职业方向为概括性介绍，具体课程设置以各高校公布的信息为准。</p></div>`;}
function specialty(id){const s=specialties[id];if(!s){location.hash='explore';return;}const matches=engineers.filter(e=>e.specialty===s.name);app.innerHTML=`<div class="page"><a class="back" href="#explore">← 返回工程专业</a><div class="detail-hero"><div><div class="eyebrow">${s.en} ENGINEERING</div><h1>${s.name}</h1><p>${s.intro}</p></div><div class="detail-mark" aria-hidden="true">${s.icon}</div></div><div class="detail-grid"><section class="card"><h3>大学里，会学习什么？</h3><ul>${s.courses.map(c=>`<li>${c}</li>`).join('')}</ul><p class="hint">不同高校的课程名称和安排可能有所不同。</p></section><section class="card"><h3>未来，可以走向哪里？</h3><p>${s.jobs}</p><h3>生活里的工程</h3><p>${s.example}</p></section></div><div class="callout"><div class="eyebrow">YOUR FIRST PROJECT</div><h3>动手试试，给好奇心一个出口。</h3><p>${s.project}</p></div><div class="section-head"><h2>这个方向的引路人</h2><a class="text-link" href="#engineers">查看所有工程师 ↗</a></div><div class="grid">${matches.length?matches.map(engineerCard).join(''):`<div class="empty wide">暂时没有这个方向的工程师开放预约。可以看看其他专业，或邀请有相关经验的前辈加入。</div>`}</div></div>`;}
function auth(mode='login',role='student'){
 if(mode==='register'&&role==='admin')role='student';
 showModal(`<div class="eyebrow">WELCOME TO TORCHLAB</div><h2>${role==='admin'?'管理员登录':'选择身份，开启你的工坊。'}</h2><div class="modal-tabs"><button class="${mode==='login'?'active':''}" data-auth="login">登录</button>${role!=='admin'?`<button class="${mode==='register'?'active':''}" data-auth="register">注册账号</button>`:''}</div><form id="auth-form"><div class="field"><label>${mode==='login'?'选择登录入口':'以哪种身份加入？'}</label><div class="role-selector">${(role==='admin'?['admin']:['student','engineer']).map(r=>`<label><input type="radio" name="role" value="${r}" ${r===role?'checked':''}> ${r==='admin'?'管理员端':r==='engineer'?'工程师端':'学生端'}</label>`).join('')}</div></div>${mode==='register'?'<div class="field"><label for="name">你的称呼</label><input id="name" name="name" maxlength="40" required autocomplete="name"></div>':''}<div class="field"><label for="email">邮箱</label><input id="email" name="email" type="email" required autocomplete="email" maxlength="254"></div><div class="field"><label for="password">密码</label><input id="password" name="password" type="password" required minlength="8" maxlength="128" autocomplete="${mode==='login'?'current-password':'new-password'}" placeholder="至少 8 位"></div>${errorBox()}<button class="button" type="submit">${mode==='login'?'登录工坊':'创建账号'} ↗</button><p class="hint">邮箱用于账号识别，当前本地版不发送验证邮件，也不提供密码找回。网站管理员可查看匹配申请与咨询记录。</p></form><button class="portal-link" id="admin-login">${role==='admin'?'返回学生 / 工程师登录':'我是管理员 →'}</button>`);
 modalBody.querySelectorAll('[data-auth]').forEach(b=>b.onclick=()=>auth(b.dataset.auth,modalBody.querySelector('input[name=role]:checked')?.value||role));
 document.querySelector('#admin-login').onclick=async()=>{if(role==='admin'){auth();return;}try{if((await api('admin-setup-status')).needed){modal.close();location.hash='admin/setup';}else auth('login','admin');}catch(e){toast(e.message);}};
 document.querySelector('#auth-form').onsubmit=e=>{e.preventDefault();formSubmit(e.target,async f=>{me=(await api(mode,Object.fromEntries(f))).user;accountLabel();modal.close();toast(mode==='login'?'欢迎回来。':'账号已创建，欢迎加入薪火工坊。');const destination=me.is_admin?'admin':me.role==='engineer'?(mode==='register'?'profile':'mentor'):'workspace';if(location.hash===`#${destination}`)await route();else location.hash=destination;});};
}
function book(id){if(!me){auth();toast('请先登录学生账号，再申请项目指导。');return;}if(me.role!=='student'){toast('请使用学生账号申请指导。');return;}const engineer=engineers.find(e=>e.id===Number(id));if(!engineer){toast('这位工程师暂未开放预约。');return;}showModal(`<div class="eyebrow">START A CONVERSATION</div><h2>向 ${esc(engineer.name)} 申请指导</h2><p>${esc(engineer.specialty)} · ${esc(engineer.fee)}</p><form id="book-form"><div class="field"><label for="title">项目名称</label><input id="title" name="title" required maxlength="100" placeholder="例如：校园自动浇水装置"></div><div class="field"><label for="question">你的想法与希望获得的帮助</label><textarea id="question" name="question" required minlength="10" maxlength="3000" placeholder="介绍项目目标、目前进展，以及你想请教的问题（至少 10 字）。"></textarea></div>${errorBox()}<button class="button" type="submit">发送匹配申请 ↗</button><p class="hint">工程师同意后即可开始聊天。涉及费用时，请先与工程师确认；本站不处理支付。</p></form>`);document.querySelector('#book-form').onsubmit=e=>{e.preventDefault();formSubmit(e.target,async f=>{await api('requests',{...Object.fromEntries(f),engineer_id:engineer.id});modal.close();toast('申请已发送，可以在“我的咨询”查看进度。');location.hash='workspace';});};}
function requestCard(r){const other=me.role==='engineer'?r.student_name:r.engineer_name;return `<article class="request-card"><span class="badge ${r.status==='pending'?'orange':''}">${esc(r.specialty)}</span><h3>${esc(r.title)}</h3><p>${me.role==='engineer'?'来自':'指导工程师'} · ${esc(other)}</p><p>${date(r.created)}${r.unread?` · <span class="badge orange">${r.unread} 条未读</span>`:''}</p><div class="actions"><a class="button secondary" href="#chat/${r.id}">${r.status==='active'?'进入聊天':'查看详情'} ↗</a>${me.role==='engineer'&&r.status==='pending'?`<button class="button" data-status="active" data-id="${r.id}">接受申请</button>`:''}</div></article>`;}
async function workspaceImpl(token){if(!me){app.innerHTML=`<div class="page"><div class="empty"><h2>你的项目旅程，从这里开始。</h2><p>登录后查看匹配进度、与工程师交流，或管理收到的指导邀请。</p><button class="button" data-login>登录 / 注册 ↗</button></div></div>`;return;}const result=await api('requests');if(token!==routeToken)return;requests=result.requests;const groups=[{status:'pending',title:'待匹配'},{status:'active',title:'正在咨询'},{status:'completed',title:'已完成'}];app.innerHTML=`<div class="page"><div class="section-head"><div><div class="eyebrow">${me.role==='engineer'?'MENTOR WORKSPACE':'MY PROJECTS'}</div><h1>${me.role==='engineer'?'让经验，有新的去处。':'每一步探索，都值得被看见。'}</h1><p>${me.role==='engineer'?'处理学生的指导邀请，继续与你的学生沟通。':'查看匹配申请，与前辈一起推进你的项目。'}</p></div>${me.role==='engineer'?'<a class="button secondary" href="#profile">编辑个人资料 ↗</a>':'<a class="button secondary" href="#engineers">寻找工程师 ↗</a>'}</div><div class="workspace-meta"><span>${requests.filter(r=>r.status==='pending').length} 个待匹配</span><span>${requests.filter(r=>r.status==='active').length} 个咨询中</span><span>${requests.filter(r=>r.status==='completed').length} 个已完成</span></div><div class="board">${groups.map(g=>`<section class="board-column"><div class="board-title"><h3>${g.title}</h3><span class="badge">${requests.filter(r=>r.status===g.status).length}</span></div>${requests.filter(r=>r.status===g.status).map(requestCard).join('')||'<p class="hint">这里暂时没有项目。</p>'}</section>`).join('')}</div>${requests.some(r=>r.status==='declined')?`<section class="callout"><h3>未通过的申请</h3>${requests.filter(r=>r.status==='declined').map(requestCard).join('')}</section>`:''}</div>`;}
async function workspace(token){await workspaceImpl(token);if(me&&token===routeToken){const signature=JSON.stringify(requests);poll=setInterval(async()=>{try{const fresh=(await api('requests')).requests;if(token===routeToken&&JSON.stringify(fresh)!==signature)route();}catch{}},3000);}}
async function chat(id,token){if(!me){location.hash='workspace';return;}requests=(await api('requests')).requests;if(token!==routeToken)return;const r=requests.find(r=>r.id===Number(id));if(!r){app.innerHTML='<div class="page"><div class="empty">无法访问该咨询。<a href="#workspace"> 返回我的咨询</a></div></div>';return;}const status={pending:'等待工程师接受申请',active:'正在咨询',completed:'项目已完成',declined:'申请未通过'}[r.status];app.innerHTML=`<div class="page"><a class="back" href="#workspace">← 返回我的咨询</a><div class="chat-layout"><aside class="card chat-profile"><div class="avatar large">${esc(r.engineer_name[0])}</div><h2>${esc(r.engineer_name)}</h2><span class="badge">${esc(r.specialty)}</span><p>${r.years} 年从业经验</p><p>${esc(r.bio||'暂无个人介绍')}</p><hr><h3>项目问题</h3><p>${esc(r.question)}</p></aside><section class="chat-panel"><div class="chat-header"><h3>${esc(r.title)}</h3><p>${esc(r.student_name)} ↔ ${esc(r.engineer_name)} · ${status}</p><details class="mobile-project"><summary>查看工程师与项目背景</summary><p>${esc(r.engineer_name)} · ${esc(r.specialty)} · ${r.years} 年经验</p><p>${esc(r.bio)}</p><p>${esc(r.question)}</p></details></div>${r.status==='active'||r.status==='completed'?`<div id="messages" class="messages" aria-label="聊天记录"></div><div id="connection-status" class="chat-status">消息每 3 秒自动更新</div>${r.status==='active'?`<form id="message-form" class="chat-composer"><label class="sr-only" for="body">消息内容</label><textarea id="body" name="body" required maxlength="3000" placeholder="聊聊你的进展，或提出新的问题…"></textarea><button class="button" type="submit">发送 ↗</button><div class="error wide" role="alert"></div></form>${me.role==='engineer'?`<div class="chat-status"><button class="button secondary small" data-complete="${r.id}">结束本次咨询</button></div>`:''}`:'<div class="chat-status">咨询已完成，聊天记录保留，只读。</div>'}`:`<div class="messages"><h3>你的匹配申请</h3><p>${esc(r.question)}</p><div class="callout"><strong>${status}</strong><p>${r.status==='pending'?'工程师接受后，这里会开启聊天。':'你可以寻找其他工程师，或重新提交更完整的项目计划。'}</p></div></div>${me.role==='engineer'&&r.status==='pending'?`<div class="chat-composer"><button class="button" data-status="active" data-id="${r.id}">接受申请，开启咨询</button><button class="button danger" data-status="declined" data-id="${r.id}">暂不接受</button></div>`:''}`}</section></div></div>`;if(r.status==='active'||r.status==='completed'){currentMessages='';await refreshMessages(r.id,token);if(token===routeToken&&r.status==='active'){poll=setInterval(()=>refreshMessages(r.id,token),3000);document.querySelector('#message-form').onsubmit=e=>{e.preventDefault();formSubmit(e.target,async f=>{await api('messages',{request_id:r.id,body:f.get('body')});e.target.reset();await refreshMessages(r.id,token);});};} }else if(r.status==='pending')poll=setInterval(async()=>{try{const fresh=(await api('requests')).requests.find(x=>x.id===r.id);if(token===routeToken&&fresh?.status!==r.status)route();}catch{}},3000);}
async function refreshMessages(id,token){try{const result=await api(`messages?request_id=${id}`);if(token!==routeToken)return;const container=document.querySelector('#messages');if(!container)return;const signature=JSON.stringify(result.messages);if(signature!==currentMessages){const atBottom=container.scrollHeight-container.scrollTop-container.clientHeight<80;const first=currentMessages==='';currentMessages=signature;container.innerHTML=result.messages.length?result.messages.map(m=>`<div class="message ${m.sender_id===me.id?'mine':''}"><small>${esc(m.sender_name)} · ${date(m.created)}</small><div class="bubble">${esc(m.body)}</div></div>`).join(''):'<p class="hint">申请已通过。介绍一下项目进展，开始你们的第一次交流吧。</p>';if(atBottom||first)container.scrollTop=container.scrollHeight;if(result.messages.length)await api('message-read',{request_id:id,last_id:result.messages.at(-1).id});}document.querySelector('#connection-status').textContent='消息每 3 秒自动更新';const fresh=(await api('requests')).requests.find(r=>r.id===id);if(token===routeToken&&fresh&&fresh.status==='completed'&&document.querySelector('#message-form'))route();}catch(e){if(token!==routeToken)return;const status=document.querySelector('#connection-status');if(status)status.textContent=e.message;}}
function profile(){if(!me){auth();location.hash='home';return;}app.innerHTML=`<div class="page profile"><div class="page-intro"><div class="eyebrow">YOUR PROFILE</div><h1>${me.role==='engineer'?'让学生认识你。':'关于你的小小档案。'}</h1><p>${me.role==='engineer'?'填写专业和经验，开启属于你的指导之旅。':'在这里更新你的称呼与兴趣。'}</p></div><form class="card" id="profile-form"><div class="field"><label>账号邮箱</label><p>${esc(me.email)}</p></div><div class="field"><label for="profile-name">你的称呼</label><input id="profile-name" name="name" value="${esc(me.name)}" required maxlength="40"></div><div class="field"><label for="specialty">${me.role==='engineer'?'主要工程方向':'感兴趣的工程方向'}</label><select id="specialty" name="specialty">${specialties.map(s=>`<option ${s.name===me.specialty?'selected':''}>${s.name}</option>`).join('')}</select></div><div class="field"><label for="bio">${me.role==='engineer'?'专业背景与可提供的帮助':'个人介绍'}</label><textarea id="bio" name="bio" maxlength="1500" placeholder="${me.role==='engineer'?'介绍你的从业经历、擅长的领域和适合指导的项目。':'说说你对工程的兴趣。'}">${esc(me.bio)}</textarea></div>${me.role==='engineer'?`<div class="field"><label for="years">从业年限</label><input id="years" type="number" name="years" min="0" max="70" required value="${me.years}"></div><div class="field"><label for="fee">指导方式</label><select id="fee" name="fee"><option ${me.fee==='公益指导'?'selected':''}>公益指导</option><option ${me.fee==='低收费 · 面议'?'selected':''}>低收费 · 面议</option></select></div><div class="field"><label class="checkbox"><input type="checkbox" name="available" ${me.available?'checked':''}> 开放学生预约</label></div><p class="hint">资料由你本人提供。当前本地版不核验资质，学生可在沟通时进一步了解你的经历。</p>`:''}${errorBox()}<div class="actions"><button class="button" type="submit">保存资料 ↗</button><button class="button secondary" type="button" id="logout">退出登录</button></div></form></div>`;document.querySelector('#profile-form').onsubmit=e=>{e.preventDefault();formSubmit(e.target,async f=>{await api('profile',{...Object.fromEntries(f),years:Number(f.get('years')||0),fee:f.get('fee')||me.fee,available:me.role==='engineer'?f.has('available'):Boolean(me.available)});me=(await api('me')).user;engineers=(await api('engineers')).engineers;accountLabel();toast('个人资料已保存。');});};document.querySelector('#logout').onclick=async()=>{try{await api('logout',{});me=null;accountLabel();location.hash='home';toast('已退出登录。');}catch(e){toast(e.message);}};}
function about(){app.innerHTML=`<div class="page about"><div class="eyebrow">ABOUT TORCHLAB</div><h1>退休的，是工作。<br>继续的，是热爱。</h1><p>工程项目的第一步，往往不是复杂的技术，而是一个愿意听你提问的人。</p><p>薪火工坊希望连接对工程感兴趣的中学生与愿意分享经验的退休工程师。让一生积累的知识，通过一次讨论、一个建议、一个共同完成的项目，继续照亮新的探索。</p><p class="quote">让一代人的经验，<br>成为下一代的起点。</p><div class="detail-grid"><section class="card"><h3>给好奇的你</h3><p>探索工程专业，寻找项目灵感，带着具体的问题向前辈请教。</p><a class="text-link" href="#explore">开始探索 ↗</a></section><section class="card"><h3>给热心的前辈</h3><p>以公益或低收费的方式分享专业经验，陪伴学生把想法变成作品。</p><button class="button secondary" data-join>加入薪火工坊 ↗</button></section></div><div class="callout"><h3>一起创造，也一起认真对待安全。</h3><p>中学生开展实验时，请让老师或监护人知情，涉及电气、工具或化学材料的操作应在具备条件的场所由成年人指导。请勿在聊天中分享身份证、家庭住址等敏感个人信息。</p></div></div>`;}
async function route(){clearInterval(poll);poll=null;const token=++routeToken;let hash=location.hash.slice(1)||'home';if(hash==='home'&&me?.is_admin)hash='admin';else if(hash==='home'&&me?.role==='engineer')hash='mentor';accountLabel();document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.hash===`#${hash.split('/')[0]}`));try{if(hash==='home'||hash==='student'||hash==='engineers'||hash.startsWith('specialty/')){engineers=(await api('engineers')).engineers;if(token!==routeToken)return;}if(hash==='home'||hash==='student')home();else if(hash==='mentor')await mentor(token);else if(hash==='admin/setup')await adminSetup();else if(hash==='admin'||hash.startsWith('admin/'))await adminPage(hash,token);else if(hash==='engineers')engineerList();else if(hash==='explore')explore();else if(hash.startsWith('specialty/'))specialty(Number(hash.split('/')[1]));else if(hash==='workspace')await workspace(token);else if(hash.startsWith('chat/'))await chat(hash.split('/')[1],token);else if(hash==='profile')profile();else if(hash==='about')about();else{location.hash='home';return;}if(token!==routeToken)return;bind();window.scrollTo(0,0);}catch(e){if(token===routeToken){app.innerHTML=`<div class="page"><div class="empty"><h3>暂时无法打开页面</h3><p>${esc(e.message)}</p><button class="button" id="retry">重新尝试</button></div></div>`;document.querySelector('#retry').onclick=route;}}}
function bind(){app.querySelectorAll('[data-book]').forEach(b=>b.onclick=()=>book(b.dataset.book));app.querySelectorAll('[data-join]').forEach(b=>b.onclick=()=>{if(me?.role==='engineer')location.hash='profile';else if(me)toast('你当前是学生账号。请退出后注册独立的工程师账号。');else auth('register','engineer');});app.querySelectorAll('[data-login]').forEach(b=>b.onclick=()=>auth('login',b.dataset.login||'student'));app.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{selectedSpecialty=b.dataset.filter;engineerList();bind();});const search=app.querySelector('#engineer-search');const runSearch=()=>{searchTerm=search.value.trim();engineerList();bind();};if(search){app.querySelector('#engineer-search-button').onclick=runSearch;search.onkeydown=e=>{if(e.key==='Enter')runSearch();};}app.querySelectorAll('[data-status]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await api('request-status',{id:Number(b.dataset.id),status:b.dataset.status});toast(b.dataset.status==='active'?'已接受申请，可以开始咨询。':'已处理这份申请。');await route();}catch(e){toast(e.message);b.disabled=false;}});app.querySelectorAll('[data-complete]').forEach(b=>b.onclick=()=>{showModal(`<h2>结束本次咨询？</h2><p>结束后双方仍可查看记录，但不能继续发送消息。请先确认项目讨论已完成。</p><button class="button" id="confirm-complete">确认结束</button>`);document.querySelector('#confirm-complete').onclick=async e=>{e.target.disabled=true;try{await api('request-status',{id:Number(b.dataset.complete),status:'completed'});modal.close();toast('本次咨询已完成。');await route();}catch(err){toast(err.message);e.target.disabled=false;}};});}
document.querySelector('#modal-close').onclick=()=>modal.close();modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close();}});document.querySelector('#account').onclick=()=>me?location.hash=me.is_admin?'admin/account':'profile':auth();document.querySelector('#search-open').onclick=()=>{showModal(`<h2>想探索什么？</h2><form id="global-search"><label for="query">专业、工程师或项目关键词</label><input id="query" name="query" required placeholder="例如：机械、机器人、纸桥"><div class="actions toolbar"><button class="button" type="submit">搜索 ↗</button></div><div id="search-results"></div></form>`);document.querySelector('#global-search').onsubmit=async e=>{e.preventDefault();const q=new FormData(e.target).get('query').trim();try{engineers=(await api('engineers')).engineers;const subjects=specialties.map((s,i)=>({...s,id:i})).filter(s=>`${s.name} ${s.desc} ${s.intro} ${s.project} ${s.courses.join(' ')}`.includes(q));const people=engineers.filter(e=>`${e.name} ${e.specialty} ${e.bio}`.includes(q));document.querySelector('#search-results').innerHTML=`${subjects.map(s=>`<p><a class="text-link search-result" href="#specialty/${s.id}">${s.name} · 认识这个专业 ↗</a></p>`).join('')}${people.map(p=>`<p><button class="button secondary small" data-result="${p.id}">${esc(p.name)} · ${esc(p.specialty)} ↗</button></p>`).join('')}${!subjects.length&&!people.length?'<p>没有找到结果，请换一个关键词。</p>':''}`;modalBody.querySelectorAll('.search-result').forEach(a=>a.onclick=()=>modal.close());modalBody.querySelectorAll('[data-result]').forEach(b=>b.onclick=()=>book(b.dataset.result));}catch(err){toast(err.message);}};};window.addEventListener('hashchange',route);
(async()=>{try{me=(await api('me')).user;accountLabel();}catch{}await route();})();

async function mentor(token){
 if(me?.role==='engineer'&&!me.is_admin){await workspace(token);return;}
 app.innerHTML=`<div class="page"><div class="page-intro"><div class="eyebrow">ENGINEER PORTAL</div><h1>让经验，有新的去处。</h1><p>工程师工作台集中处理学生邀请、正在指导的项目和已完成的咨询。</p></div><div class="journey"><a href="#workspace"><span class="num">01</span><div><h3>待匹配</h3><p>了解学生想法，决定接受邀请</p></div></a><a href="#workspace"><span class="num">02</span><div><h3>正在咨询</h3><p>回答问题，共同推进项目</p></div></a><a href="#workspace"><span class="num">03</span><div><h3>已完成</h3><p>回看讨论，记录每一步成长</p></div></a></div><div class="empty"><h3>${me?.is_admin?'你正在预览工程师端':'进入你的工程师工作台'}</h3><p>${me?.is_admin?'每位工程师只能查看自己的指导项目。你可以在管理后台查看全部项目。':me?'当前登录的是学生账号，请退出后使用工程师账号登录。':'使用工程师账号登录后，可以处理邀请和查看咨询消息。'}</p>${!me?'<button class="button" data-login="engineer">工程师登录 ↗</button>':me.is_admin?'<a class="button" href="#admin/requests">查看全部指导项目 ↗</a>':'<a class="button" href="#profile">管理当前账号 ↗</a>'}</div></div>`;
}
async function adminSetup(){
 const needed=(await api('admin-setup-status')).needed;
 app.innerHTML=`<div class="page profile"><div class="page-intro"><div class="eyebrow">ADMINISTRATOR</div><h1>${needed?'创建你的管理员账号。':'管理员已设置。'}</h1><p>${needed?'仅网站所有者可使用本机初始化密钥创建管理员。完成后，此入口自动关闭。':'请使用已设置的管理员邮箱与密码登录。'}</p></div>${needed?`<form class="card" id="admin-setup-form"><div class="field"><label for="setup-key">管理员初始化密钥</label><input id="setup-key" name="setup_key" type="password" required autocomplete="off"><p class="hint">从网站文件夹的 data/admin-setup-key.txt 复制密钥。</p></div><div class="field"><label for="admin-name">管理员称呼</label><input id="admin-name" name="name" required maxlength="40" autocomplete="name"></div><div class="field"><label for="admin-email">管理员邮箱</label><input id="admin-email" name="email" type="email" required autocomplete="email"></div><div class="field"><label for="admin-password">密码</label><input id="admin-password" name="password" type="password" required minlength="8" maxlength="128" autocomplete="new-password"><p class="hint">若使用已注册邮箱，请填写该账号现有的密码。</p></div>${errorBox()}<button class="button" type="submit">创建管理员账号 ↗</button></form>`:'<button class="button" data-login="admin">管理员登录 ↗</button>'}</div>`;
 if(needed)document.querySelector('#admin-setup-form').onsubmit=e=>{e.preventDefault();formSubmit(e.target,async f=>{await api('admin-setup',Object.fromEntries(f));toast('管理员已创建，请登录。');auth('login','admin');location.hash='admin';});};
}
const statusName=s=>({pending:'待匹配',active:'正在咨询',completed:'已完成',declined:'未通过'}[s]||s);
async function adminPage(hash,token){
 if(!me?.is_admin){app.innerHTML=`<div class="page"><div class="empty"><h2>管理员入口</h2><p>${me?'当前账号没有管理员权限。请退出后使用管理员账号登录。':'使用管理员账号查看全站用户、匹配申请和聊天记录。'}</p>${me?'<a class="button" href="#profile">管理当前账号 ↗</a>':'<button class="button" data-login="admin">管理员登录 ↗</button>'}</div></div>`;return;}
 if(hash==='admin/account'){app.innerHTML=`<div class="page profile"><div class="card"><div class="eyebrow">ADMIN ACCOUNT</div><h1>管理员账号</h1><h3>${esc(me.name)}</h3><p>${esc(me.email)}</p><div class="actions"><a class="button" href="#admin">返回管理总览</a><button class="button secondary" id="admin-logout">退出登录</button></div></div></div>`;document.querySelector('#admin-logout').onclick=async()=>{try{await api('logout',{});me=null;accountLabel();location.hash='home';}catch(e){toast(e.message);}};return;}
 if(hash.startsWith('admin/chat/')){
 const result=await api('admin/conversation?request_id='+encodeURIComponent(hash.split('/')[2]));if(token!==routeToken)return;const r=result.request;
 app.innerHTML=`<div class="page"><a class="back" href="#admin/requests">← 返回全部咨询</a><div class="page-intro"><div class="eyebrow">CONVERSATION REVIEW</div><h1>${esc(r.title)}</h1><p>${esc(r.student_name)} ↔ ${esc(r.engineer_name)} · ${statusName(r.status)}</p></div><div class="callout"><h3>申请内容</h3><p class="preserve">${esc(r.question)}</p></div><div class="chat-panel"><div class="chat-header"><h3>全部聊天记录</h3><p>管理员查看模式 · 不会改变参与者的未读状态</p></div><div class="admin-messages">${result.messages.length?result.messages.map(m=>`<div class="message"><small>${esc(m.sender_name)} · ${date(m.created)}</small><div class="bubble">${esc(m.body)}</div></div>`).join(''):'<p class="hint">该咨询暂无聊天消息。</p>'}</div></div></div>`;return;
 }
 const result=await api('admin/overview');if(token!==routeToken)return;
 let selected=hash==='admin/users'?'users':hash==='admin/requests'?'requests':'overview';
 app.innerHTML=`<div class="page"><div class="section-head"><div><div class="eyebrow">ADMINISTRATION</div><h1>工坊的每一次连接，都在这里。</h1><p>查看全站用户、工程师资料、匹配进度与聊天记录。</p></div><button class="button secondary" id="admin-refresh">刷新数据 ↻</button></div><div class="admin-tabs"><a class="chip ${selected==='overview'?'active':''}" href="#admin">总览</a><a class="chip ${selected==='users'?'active':''}" href="#admin/users">全部用户</a><a class="chip ${selected==='requests'?'active':''}" href="#admin/requests">全部咨询与聊天</a></div><div class="admin-stats"><div class="card"><span>学生</span><strong>${result.users.filter(u=>u.role==='student'&&!u.is_admin).length}</strong></div><div class="card"><span>工程师</span><strong>${result.users.filter(u=>u.role==='engineer'&&!u.is_admin).length}</strong></div><div class="card"><span>匹配申请</span><strong>${result.requests.length}</strong></div><div class="card"><span>聊天消息</span><strong>${result.message_count}</strong></div></div><div class="toolbar"><label class="sr-only" for="admin-search">搜索全站数据</label><input id="admin-search" placeholder="搜索姓名、邮箱、项目或专业"><label class="sr-only" for="admin-filter">筛选</label><select id="admin-filter" class="admin-filter">${selected==='users'?'<option value="all">全部身份</option><option value="student">学生</option><option value="engineer">工程师</option><option value="admin">管理员</option>':'<option value="all">全部状态</option><option value="pending">待匹配</option><option value="active">正在咨询</option><option value="completed">已完成</option><option value="declined">未通过</option>'}</select></div><div id="admin-data"></div><p class="hint">管理员能查看全站业务数据；账号密码、登录令牌和初始化密钥不会显示。</p></div>`;
 const render=()=>{const q=document.querySelector('#admin-search').value.trim().toLowerCase(),filter=document.querySelector('#admin-filter').value;
 if(selected==='users'){const users=result.users.filter(u=>(filter==='all'||(u.is_admin?'admin':u.role)===filter)&&`${u.name} ${u.email} ${u.specialty} ${u.bio}`.toLowerCase().includes(q));document.querySelector('#admin-data').innerHTML=`<div class="grid">${users.map(u=>`<article class="card"><span class="badge">${roleName(u)}</span><h3>${esc(u.name)}</h3><p class="preserve">${esc(u.email)}</p><p>${esc(u.specialty)}${u.role==='engineer'?` · ${u.years} 年经验 · ${u.available?'开放预约':'暂停预约'}`:''}</p><p class="preserve">${esc(u.bio||'暂无个人介绍')}</p>${u.role==='engineer'?`<p>${esc(u.fee)}</p>`:''}<small>注册于 ${date(u.created)}</small></article>`).join('')||'<div class="empty wide">没有匹配的用户。</div>'}</div>`;
 }else{const rows=result.requests.filter(r=>(filter==='all'||r.status===filter)&&`${r.title} ${r.question} ${r.student_name} ${r.engineer_name} ${r.specialty}`.toLowerCase().includes(q));document.querySelector('#admin-data').innerHTML=`<div class="grid">${rows.map(r=>`<article class="card"><span class="badge">${statusName(r.status)}</span><h3>${esc(r.title)}</h3><p>${esc(r.student_name)} ↔ ${esc(r.engineer_name)}</p><p>${esc(r.specialty)} · ${r.message_count} 条消息</p><p class="preserve">${esc(r.question)}</p><a class="button secondary" href="#admin/chat/${r.id}">查看申请与聊天记录 ↗</a></article>`).join('')||'<div class="empty wide">暂无匹配申请。学生提交项目后会出现在这里。</div>'}</div>`;}};
 render();document.querySelector('#admin-search').oninput=render;document.querySelector('#admin-filter').onchange=render;document.querySelector('#admin-refresh').onclick=route;
}
